### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by lauken13** [lauken13/mrpkit#38]
**Survey Data**

- [x] error occurs if adding extra survey data that has less rows than the main data
- [x] warning occurs if adding a column that has a duplicate name
- [x] error occurs if there is an input dimension mismatch when creating a new survey data obj
- [x] error occurs if survey weights do not match the number of rows in survey data
- [ ] error if survey design is not specified in a survey package consistent way
- [x] error if weights with NAs are given
- [x] error if not same number of questions and responses
- [x] error if provided responses don't correspond to actual factor levels in the data
- [x] print method produces expected output

**SurveyQuestion**

- [x] error if 'name' specified incorrectly
- [x] error if 'col_names' specified incorrectly
- [x] error if 'values_map' specified incorrectly
- [x] warning if duplicated values in 'values_map'
- [x] error if not a many to one mapping
- [x] print method produces expected output
 
**SurveyFit**

- [x] population_predict returns object with the right structure
- [x] a custom `population_predict` method works properly
- [x] error if a custom `population_predict` method is required but not provided
- [x] plot method works properly and that appearance doesn't change (note: done in PR #75)
- [x] aggregate method returns objects with correct structure (with and without 'by')
- [ ] poststratification error is given if poststrat table hasn't been created (this one is hard to check in aggregate because a postatrat matrix is needed to fit a model)
- [x] predictions for a given model (brms, rstanarm, lme4) match a presaved benchmark
- [x] warning if fitting with functionality other than lme4, brms, rstanarm (because custom predicition method will be needed
- [x] error if sim_posterior_epred() is used with a non-glmerMod
- [x] error if poststrat table hasn't been created yet
- [ ] print method produces expected output
- [x] fit method returns fitted model object
- [x] map method returns map object

**SurveyMap**

- [x] error if samp obj is not a SurveyData object
- [x] error if popn_obj is not SurveyData object
- [x] add method throws error if existing column has the same name
- [ ] print method does not fail if there are unlinked/mapped columns
- [x] print method produces expected output (note: done in PR #72)
Check for a different scenarios that new data has the correct levels:
- [x] Svy: 18-25, 26-45, 46; Popn 18 - 45, 46+
- [x] Svy: 18-25, 26+; Popn 18-25, 26-34, 35+
- [ ] Svy: 18-25, 26-30, 31- 40, 41-55, 56+; 18- 25, 26-35,36 - 45, 46-55, 56+
Check that a subset of levels in the raw sample data matches the new sample data
- [x] Svy: 18-25, 26-45, 46; Popn 18 - 45, 46+
- [x] Svy: 18-25, 26+; Popn 18-25, 26-34, 35+
- [ ] Svy: 18-25, 26-30, 31- 40, 41-55, 56+; 18- 25, 26-35,36 - 45, 46-55, 56+
Check that a subset of levels in the raw population data matches the new population data
- [x] Svy: 18-25, 26-45, 46; Popn 18 - 45, 46+
- [x] Svy: 18-25, 26+; Popn 18-25, 26-34, 35+
- [ ] Svy: 18-25, 26-30, 31- 40, 41-55, 56+; 18- 25, 26-35,36 - 45, 46-55, 56+
- [x] error if model fit is other than binomial/bernoulli family
- [x] error if variables in formula aren't in data
- [x] error if data hasn't been mapped yet
- [x] error if `data` is given as an argument
- [x] fit errors if the rhs of the model are not column names of the poststrat matrix (#20)
- [x] stan_glmer runs with binomial formulation
- [x] stan_glm runs with binomial formulation
- [x] brm runs with binomial formulation
- [x] lme4 runs with binomial formulation
- [x] custom model fitting method works

Other validation
- [ ] validate function fails when map name isn't in population
- [ ] validate function fails when map name isn't in the sample
- [ ] validate function throws error when map levels aren't in the population
- [ ] validate function throws error when map levels aren't in the sample
- [ ] warning if all of the sample data variables are in the population

**End to end:**

- [ ] no warnings are outputted in an end to end run of the code with lme4
- [ ] no warnings are outputted in an end to end run of the code with brms
- [ ] no warnings are outputted in an end to end run of the code with rstanarm
- [ ] example code MRP estimate is close to truth using lme4
- [ ] example code MRP estimate is close to truth using brms
- [ ] example code MRP estimate is close to truth using rstanarm
